apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: petclinic
spec:
  host: app-petclinic-uat.apps-crc.testing
status:
  ingress:
  - conditions:
    host: app-petclinic-uatr.apps-crc.testing
