apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus2
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cicd-project
  source:
    path: gitops/cicd/nexus2
    repoURL: https://github.com/pittar/argocd-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress
  sync:
    comparedTo:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        path: gitops/cicd/nexus2
        repoURL: https://github.com/pittar/argocd-demo.git
        targetRevision: HEAD
