apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: petclinic
spec:
  host: app-petclinic-dev.apps.example.com
status:
  ingress:
  - conditions:
    host: app-petclinic-dev.apps.example.com
