apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: petclinic
    app.kubernetes.io/component: petclinic
    app.kubernetes.io/instance: petclinic
    app.kubernetes.io/name: java
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: "8"
  name: petclinic
  namespace: cicd
spec:
  lookupPolicy:
    local: false
